spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/gym?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: V170sh@229O
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        #devtools:
        #restart:
        #enabled: true
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
      #defer-datasource-initialization: true
      #logging:
      #level:
      #org.hibernate.SQLQuery: TRACE
      #org.hibernate.type.descriptor: TRACE
      #app:
      #default:
      #admin:
      #password:
      #Cloudinary Properties
      #cloudinary:
      #api-key:
      #api-secret:
      #cloud-name:
      sql:
      init:
      mode: always