spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/gym?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: V170sh@229O
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        #devtools:
        #restart:
        #enabled: true
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  security:
    user:
      name: todor
      password: todor
      roles: ADMIN, MODERATOR

logging:
  level:
    org.springframework.security: DEBUG
    #org.hibernate.SQLQuery: TRACE
    #org.hibernate.type.descriptor: TRACE
    #Cloudinary Properties
    #cloudinary:
    #api-key:
  #api-secret:
  #cloud-name:

app:
  default:
    admin:
      password: moderator
    moderator:
      password: moderator
    user:
      password: johndoe